# Generated by Django 3.2.7 on 2021-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='foxtonmedia.co.ke'),
            preserve_default=False,
        ),
    ]
